apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - values-configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - fluxinstance.yaml
  - gitrepository.yaml
  - cluster-kustomization.yaml
